Testing...
Signed-off-by: Kenneth Tran <kennethtran93@users.noreply.github.com>

diff --git a/.github/workflows/get-build-command.yml b/.github/workflows/get-build-command.yml
--- a/.github/workflows/get-build-command.yml
+++ b/.github/workflows/get-build-command.yml
@@ -13,45 +13,55 @@ jobs:
           GH_GH: ${{ toJson(github) }}
         run: |
           printenv
+          jq
       - name: Artifact URL Info
         id: arts
         env:
           GH_API: ${{ github.event.client_payload.github.payload.repository.url }}
           GH_RUNID: ${{ github.event.client_payload.slash_command.arg1 }}
+          GH_BRANCH: ${{ github.event.client_payload.pull_request.head.ref }}
         run: |
+          API_RUNS="$GH_API/actions/runs"
           echo "Run ID from Arg1:  $GH_RUNID"
           if [[ -z $GH_RUNID ]]; then
-            echo "::set-output name=result::NO_RUNID"
-            exit 1
+            echo "No Run ID Given.  Using latest run from this PR Branch
+            // https://api.github.com/repos/:owner/:repo/actions/runs?event=pull_request&status=success&branch=:branch
+            RUNS=$(curl -sf $API_RUNS?event=pull_request&status=success&branch=$GH_BRANCH)
+            EC=$?
+            if [[ $EC != 0 ]]; then
+              echo "Curl was not successful - returned $EC"
+              echo "::set-output name=result::FAILED"
+              echo "::set-output name=message::Internal Error / Could not fetch info from GitHub API at this time."
+              exit $EC
+            fi
+            if [[ $(jq --raw-output $RUNS '.total_count') -eq 0 ]]; then
+              echo "No successful PR runs were made from branch $GH_BRANCH yet."
+              echo "::set-output name=result::FAILED"
+              echo "::set-output name=message::No Successful PR Runs were made from this branch ($GH_BRANCH) yet."
+              exit 1
+            fi
+            GH_RUNID=$(jq --raw-output $RUNS '.workflow_runs[0].id')
+            echo "Using RunID of $GH_RUNID parsed from branch $GH_BRANCH runs"
           fi
           echo "Artifact URL:  $GH_API/actions/runs/$GH_RUNID/artifacts"
           ARTS=$(curl -sf $GH_API/actions/runs/$GH_RUNID/artifacts)
           if [[ $? != 0 ]]; then
-            echo "::set-output name=result::ARTS_FAILED"
-            echo "::set-output name=message::jq --raw-output $ARTS .message
+            echo "::set-output name=result::FAILED"
+            echo "::set-output name=message::Received Error Message: $(jq --raw-output $ARTS '.message')"
             exit 2
           fi
-          jq
           echo "$ARTS"
-      - name: Reply No Arg Error in PR
-        if: failure() && steps.arts.outputs.result == 'NO_RUNID'
+      - name: Reply Error in PR
+        if: failure() && steps.arts.outputs.result == 'FAILURE'
         uses: peter-evans/create-or-update-comment@v1.4.2
         with:
           token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
           repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
           issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
           body: |
-            The `get-build` command was executed with no arguments.  A run id is required at this time.
-          reactions: eyes,confused
-      - name: Reply Invalid Run ID in PR
-        if: failure() && steps.arts.outputs.result == 'ARTS_FAILED'
-        uses: peter-evans/create-or-update-comment@v1.4.2
-        with:
-          token: ${{ secrets.REPO_ACCESS_TOKEN_WORKFLOW }}
-          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
-          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
-          body: |
-            The `get-build` command did not get expected response.  Please check the run ID entered.
+            The `get-build` command did not execute successfully.  Additional information, if any, will be noted below.
+
+            ${{ steps.arts.outputs.message }}
           reactions: eyes,confused
       - name: Create comment in PR
         uses: peter-evans/create-or-update-comment@v1.4.2
