Testing...
Signed-off-by: Kenneth Tran <kennethtran93@users.noreply.github.com>

diff --git a/.github/workflows/get-build-command.yml b/.github/workflows/get-build-command.yml
--- a/.github/workflows/get-build-command.yml
+++ b/.github/workflows/get-build-command.yml
@@ -29,25 +29,26 @@ jobs:
             EC=$?
             if [[ $EC != 0 ]]; then
               echo "Curl was not successful - returned $EC"
-              echo "::set-output name=result::FAILED"
-              echo "::set-output name=message::Internal Error / Could not fetch info from GitHub API at this time."
+              echo ::set-output name=result::"FAILED"
+              echo ::set-output name=message::"Internal Error / Could not fetch info from GitHub API at this time."
               exit $EC
             fi
             if [[ $(cat curl_latest.json | jq --raw-output '.total_count') -eq 0 ]]; then
               echo "No successful PR runs were made from branch $GH_BRANCH yet."
-              echo "::set-output name=result::FAILED"
-              echo "::set-output name=message::No Successful PR Runs were made from this branch ($GH_BRANCH) yet."
+              echo ::set-output name=result::"FAILED"
+              echo ::set-output name=message::"No Successful PR Runs were made from branch $GH_BRANCH yet."
               exit 1
             fi
             GH_RUNID=$(cat curl_latest.json | jq --raw-output '.workflow_runs[0].id')
             echo "Using RunID of $GH_RUNID parsed from branch $GH_BRANCH runs"
           fi
           echo "Artifact URL:  $GH_API/actions/runs/$GH_RUNID/artifacts"
-          ARTS=$(curl -sf $GH_API/actions/runs/$GH_RUNID/artifacts)
-          if [[ $? != 0 ]]; then
-            echo "::set-output name=result::FAILED"
-            echo "::set-output name=message::Received Error Message: $(jq --raw-output $ARTS '.message')"
-            exit 2
+          curl -sf $GH_API/actions/runs/$GH_RUNID/artifacts > curl_artifacts.json
+          EC=$?
+          if [[ $EC != 0 ]]; then
+            echo ::set-output name=result::"FAILED"
+            echo ::set-output name=message::"Received Error Message: $(cat curl_artifacts.json | jq --raw-output '.message')"
+            exit $EC
           fi
           echo "$ARTS"
       - name: Reply Error in PR
